In [1]:
import numpy as np

In [3]:


# Matrix
matrix = np.array([[1, 0.2, 0.5],
                   [0.2, 1, 0.8],
                   [0.5, 0.8, 1]])



# (a) Computing the inverse of the matrix
inverse_matrix = np.linalg.inv(matrix)
print("(a) Inverse of the matrix:\n", inverse_matrix)



# (b) Computing the determinant of the matrix
determinant = np.linalg.det(matrix)
print("(b) Determinant of the matrix:", determinant)



# (c) Decomposing the matrix
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("(c) Eigenvalues:\n", eigenvalues)
print("    Eigenvectors:\n", eigenvectors)



# (d) Transforming the matrix
transformation_matrix = np.array([[2, 0, 0],
                                  [0, 3, 0],
                                  [0, 0, 1]])
transformed_matrix = matrix.dot(transformation_matrix)
print("(d) Transformed matrix (matrix multiplication):\n", transformed_matrix)

(a) Inverse of the matrix:
 [[ 1.56521739  0.86956522 -1.47826087]
 [ 0.86956522  3.26086957 -3.04347826]
 [-1.47826087 -3.04347826  4.17391304]]
(b) Determinant of the matrix: 0.2299999999999999
(c) Eigenvalues:
 [2.04100779 0.82188052 0.13711169]
    Eigenvectors:
 [[-0.43721717 -0.85359707 -0.28321933]
 [-0.59931898  0.51133314 -0.61591816]
 [-0.67056536  0.09955128  0.73514055]]
(d) Transformed matrix (matrix multiplication):
 [[2.  0.6 0.5]
 [0.4 3.  0.8]
 [1.  2.4 1. ]]
